name: build
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory contents
        run: ls -la

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.6.2

      - name: Change to correct directory
        run: cd $GITHUB_WORKSPACE

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Ensure pnpm store path exists
        run: mkdir -p $STORE_PATH

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          cd $GITHUB_WORKSPACE
          pnpm install

      - name: Run validate
        run: |
          echo "Running validate..."
          cd $GITHUB_WORKSPACE
          pnpm run validate

      - name: Run build
        run: |
          echo "Running build..."
          cd $GITHUB_WORKSPACE
          pnpm run build
