name: lint
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.4.1
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install

      - name: Run lint
        run: |
          echo "Running lint..."
          pnpm run lint
